"""Freqtrade bridge — export AetherBot strategies to freqtrade format.

LICENSE BOUNDARY (read this before changing anything here):
freqtrade is GPL-3.0 licensed. AetherBot is MIT. To keep AetherBot
MIT-clean, this bridge copies NO freqtrade source code. It only
GENERATES a strategy file that subclasses freqtrade's IStrategy,
re-basing YOUR OWN strategy code (which AetherBot's Strategy interface
was already designed to be column-compatible with: enter_long /
exit_long / populate_indicators / populate_entry_trend /
populate_exit_trend). Run the exported file inside a freqtrade
installation (e.g. the freqtrade-develop tree) — the two projects
interoperate; their code does not merge.

The export is a starting point: freqtrade extras (informative pairs,
order types, protections) may need hand-tuning, and the result should
be backtested inside freqtrade before trusting it.
"""
from __future__ import annotations

import inspect
import re

HEADER = '''"""Freqtrade strategy generated by AetherBot's freqtrade bridge.

Your AetherBot strategy, re-based on freqtrade's IStrategy
(column-compatible by design: enter_long / exit_long). No freqtrade
code was copied — this file only re-bases YOUR strategy. Review and
backtest inside freqtrade before any live use. Live trading can lead
to TOTAL LOSS of capital.
"""
from freqtrade.strategy import IStrategy
import pandas as pd


'''


def export_to_freqtrade(strategy_cls, out_path=None) -> str:
    """Generate a freqtrade-compatible strategy module from an AetherBot
    Strategy subclass. Returns the generated source; writes it to
    out_path if given."""
    from .engine.strategy.interface import Strategy
    if not (isinstance(strategy_cls, type)
            and issubclass(strategy_cls, Strategy)):
        raise TypeError("export_to_freqtrade expects an AetherBot "
                        "Strategy subclass (got %r)" % strategy_cls)
    source = inspect.getsource(strategy_cls)
    # re-base: class X(Strategy) [or (Strategy, ...)] -> class X(IStrategy)
    new_source, n = re.subn(
        r"(class\s+\w+\s*\()\s*Strategy\s*(\)|,)",
        r"\1IStrategy\2", source)
    if n == 0:
        raise ValueError(
            "strategy %r does not directly subclass Strategy; the "
            "bridge only supports direct Strategy subclasses"
            % strategy_cls.__name__)
    # ensure INTERFACE_VERSION = 3 attribute after the class line
    if "INTERFACE_VERSION" not in new_source:
        new_source = re.sub(
            r"(class\s+\w+\s*\(\s*IStrategy\s*\)\s*:\n)",
            r"\1    INTERFACE_VERSION = 3\n\n", new_source, count=1)
    generated = HEADER + new_source
    if out_path:
        with open(out_path, "w") as f:
            f.write(generated)
    return generated


if __name__ == "__main__":  # pragma: no cover
    print(__doc__)
